name: Deploy to Production

on:
  push:
    branches:
      - prod

jobs:
  deploy:
    runs-on: ubuntu-latest
    permissions:
      id-token: write
      contents: read

    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Authenticate to Google Cloud
        id: auth
        uses: google-github-actions/auth@v1
        with:
          workload_identity_provider: ${{ secrets.GCP_WORKLOAD_IDENTITY_PROVIDER_PROD }}
          service_account: ${{ secrets.GCP_SERVICE_ACCOUNT_PROD }}

      - name: Set up GCloud CLI
        uses: google-github-actions/setup-gcloud@v1
        with:
          project_id: ${{ secrets.GCP_PROJECT_ID_PROD }}

      - name: Who am I
        run: |
          gcloud config get-value account
          gcloud auth list

      - name: Build Docker image
        run: |
          docker build -t us-east4-docker.pkg.dev/${{ secrets.GCP_PROJECT_ID_PROD }}/hypergoat-web/hypergoat-staff-prod -f ./Dockerfile .

      - name: Configure Docker for Artifact Registry
        run: |
          gcloud auth configure-docker us-east4-docker.pkg.dev --quiet

      - name: Push Docker image to Artifact Registry
        run: |
          docker push us-east4-docker.pkg.dev/${{ secrets.GCP_PROJECT_ID_PROD }}/hypergoat-web/hypergoat-staff-prod

      - name: Deploy to Cloud Run (Prod)
        run: |
          gcloud run deploy hypergoat-staff-prod \
            --image us-east4-docker.pkg.dev/${{ secrets.GCP_PROJECT_ID_PROD }}/hypergoat-web/hypergoat-staff-prod \
            --region ${{ secrets.GCP_REGION_PROD }} \
            --platform managed \
            --allow-unauthenticated \
            --quiet