name: Deploy to Staging (Dev)

on:
  push:
    branches:
      - staging

jobs:
  deploy:
    runs-on: ubuntu-latest
    environment: staging
    permissions:
      id-token: write
      contents: read
    env:
      NEXT_PUBLIC_FIREBASE_API_KEY: ${{ secrets.NEXT_PUBLIC_FIREBASE_API_KEY }}
      NEXT_PUBLIC_FIREBASE_AUTH_DOMAIN: ${{ secrets.NEXT_PUBLIC_FIREBASE_AUTH_DOMAIN }}
      NEXT_PUBLIC_FIREBASE_PROJECT_ID: ${{ secrets.NEXT_PUBLIC_FIREBASE_PROJECT_ID }}
      FIREBASE_PROJECT_ID: ${{ secrets.FIREBASE_PROJECT_ID }}
      FIREBASE_CLIENT_EMAIL: ${{ secrets.FIREBASE_CLIENT_EMAIL }}
      FIREBASE_PRIVATE_KEY: ${{ secrets.FIREBASE_PRIVATE_KEY }}

    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Authenticate to Google Cloud
        uses: google-github-actions/auth@v1
        with:
          workload_identity_provider: ${{ secrets.GCP_WORKLOAD_IDENTITY_PROVIDER }}
          service_account: ${{ secrets.GCP_SERVICE_ACCOUNT }}

      - name: Set up GCloud CLI
        uses: google-github-actions/setup-gcloud@v1
        with:
          project_id: ${{ secrets.GCP_PROJECT_ID }}

      - name: Build Docker image
        run: |
          docker build -t us-east4-docker.pkg.dev/${{ secrets.GCP_PROJECT_ID }}/hypergoat-web/hypergoat-staff-dev -f ./Dockerfile .

      - name: Configure Docker for Artifact Registry
        run: |
          gcloud auth configure-docker us-east4-docker.pkg.dev --quiet

      - name: Push Docker image to Artifact Registry
        run: |
          docker push us-east4-docker.pkg.dev/${{ secrets.GCP_PROJECT_ID }}/hypergoat-web/hypergoat-staff-dev

      - name: Deploy to Cloud Run (Dev)
        run: |
          gcloud run deploy hypergoat-staff-dev \
            --image us-east4-docker.pkg.dev/${{ secrets.GCP_PROJECT_ID }}/hypergoat-web/hypergoat-staff-dev \
            --region ${{ secrets.GCP_REGION }} \
            --platform managed \
            --allow-unauthenticated \
            --quiet
